show_for_members:
  type: bool
  default: true
show_for_anon:
  type: bool
  default: true
display_on_mobile:
  type: bool
  default: false
display_on_desktop:
  type: bool
  default: true
display_on_homepage:
  type: bool
  default: true
url_must_contain:
  type: list
  list_type: simple
  # default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*
  default: / # this is for only showing banner on home page 
dismissible:
  type: bool
  default: false
collapsible:
  type: bool
  default: false
default_collapsed_state:
  type: enum
  default: collapsed
  choices:
    - expanded
cookie_lifespan:
  type: enum
  default: none
  choices:
    - minute
    - day
    - week
    - month
    - year
cookie_name:
  type: string
  default: "v1"
full_width_banner:
  type: bool
  default: true
swap_default_positioning:
  type: bool
  default: false
plugin_outlet:
  type: enum
  default: "below-site-header"
  choices:
    - "below-site-header"
    - "above-main-container"
  refresh: true
banner_background_image:
  type: string
  default: ""
banner_background_image_dark:
  type: string
  default: ""
background_color:
  type: string
  default: ""
background_color_dark:
  type: string
  default: ""
primary_text_color:
  type: string
  default: "#141414"
primary_text_color_dark:
  type: string
  default: ""
secondary_text_color:
  type: string
  default: "#FF6C00"
secondary_text_color_dark:
  type: string
  default: ""
link_text_color:
  type: string
  default: "#0f82af"
link_text_color_dark:
  type: string
  default: ""
main_heading_content:
  type: string
  textarea: false
  default: ""
first_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">Image 1</div>
    </div>
second_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        <img src="https://placehold.co/300x250/orange/white?text=Image+2" alt="Image 2" style="width:100%;height:100%;object-fit:cover;margin:0;border:0;display:block;">
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">Image 2</div>
    </div>
third_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        <img src="https://placehold.co/300x250/orange/white?text=Image+3" alt="Image 3" style="width:100%;height:100%;object-fit:cover;margin:0;border:0;display:block;">
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">Image 3</div>
    </div>
fourth_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        <img src="https://placehold.co/300x250/orange/white?text=Image+4" alt="Image 4" style="width:100%;height:100%;object-fit:cover;margin:0;border:0;display:block;">
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">Image 4</div>
    </div>
fifth_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        <img src="https://placehold.co/300x250/orange/white?text=Image+5" alt="Image 5" style="width:100%;height:100%;object-fit:cover;margin:0;border:0;display:block;">
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">Image 5</div>
    </div>
first_column_size:
  type: string
  default: "48%"
second_column_size:
  type: string
  default: "13%"
third_column_size:
  type: string
  default: "13%"
fourth_column_size:
  type: string
  default: "13%"
fifth_column_size:
  type: string
  default: "13%"
first_column_icon:
  type: string
  default: ""
second_column_icon:
  type: string
  default: ""
third_column_icon:
  type: string
  default: ""
fourth_column_icon:
  type: string
  default: ""
fifth_column_icon:
  type: string
  default: ""
