show_for_members:
  type: bool
  default: true
show_for_anon:
  type: bool
  default: true
display_on_mobile:
  type: bool
  default: false
display_on_desktop:
  type: bool
  default: true
display_on_homepage:
  type: bool
  default: true
url_must_contain:
  type: list
  list_type: simple
  # default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*
  default: / # this is for only showing banner on home page 
dismissible:
  type: bool
  default: false
collapsible:
  type: bool
  default: false
default_collapsed_state:
  type: enum
  default: collapsed
  choices:
    - expanded
cookie_lifespan:
  type: enum
  default: none
  choices:
    - minute
    - day
    - week
    - month
    - year
cookie_name:
  type: string
  default: "v1"
full_width_banner:
  type: bool
  default: true
swap_default_positioning:
  type: bool
  default: false
plugin_outlet:
  type: enum
  default: "below-site-header"
  choices:
    - "below-site-header"
    - "above-main-container"
  refresh: true
banner_background_image:
  type: string
  default: ""
banner_background_image_dark:
  type: string
  default: ""
background_color:
  type: string
  default: ""
background_color_dark:
  type: string
  default: ""
primary_text_color:
  type: string
  default: "#141414"
primary_text_color_dark:
  type: string
  default: ""
secondary_text_color:
  type: string
  default: "#FF6C00"
secondary_text_color_dark:
  type: string
  default: ""
link_text_color:
  type: string
  default: "#0f82af"
link_text_color_dark:
  type: string
  default: ""
main_heading_content:
  type: string
  textarea: false
  default: ""
first_column_content:
  type: string
  textarea: true
  default: |
    <div class="first-content" style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <p class="first-line" style="margin:0;">Welcome to</p>
      <p class="second-line" style="margin:0;">Ventura Community</p>
      <p class="third-line" style="margin:0;margin-top:8px;">All your market conversations, at one place</p>
    </div>
second_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        <img src="https://placehold.co/300x250/orange/white?text=Product+updates" alt="Product updates" style="width:100%;height:100%;object-fit:cover;margin:0;border:0;display:block;">
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">Product updates</div>
    </div>
second_column_url:
  type: string
  default: "/c/product-updates"    # e.g. "/c/your-category-slug" or full URL

third_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        <img src="https://placehold.co/300x250/orange/white?text=Developer+APIs" alt="Developer APIs" style="width:100%;height:100%;object-fit:cover;margin:0;border:0;display:block;">
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">Developer APIs</div>
    </div>
third_column_url:
  type: string
  default: "/c/developer-api"

fourth_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        <img src="https://placehold.co/300x250/orange/white?text=Feature+Request" alt="Feature+Request" style="width:100%;height:100%;object-fit:cover;margin:0;border:0;display:block;">
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">Feature+Request</div>
    </div>
fourth_column_url:
  type: string
  default: "/c/feature-request"

fifth_column_content:
  type: string
  textarea: true
  default: |
    <div style="display:flex;flex-direction:column;height:100%;min-height:0;width:100%;box-sizing:border-box;padding:8px 0;margin:0;">
      <div style="flex:1;min-height:0;width:100%;">
        <img src="https://placehold.co/300x250/orange/white?text=General" alt="General" style="width:100%;height:100%;object-fit:cover;margin:0;border:0;display:block;">
      </div>
      <div style="font-size:16px;font-weight:700;text-align:center;margin-top:8px;color:#333">General</div>
    </div>
fifth_column_url:
  type: string
  default: "/c/general"
first_column_size:
  type: string
  default: "48%"
second_column_size:
  type: string
  default: "13%"
third_column_size:
  type: string
  default: "13%"
fourth_column_size:
  type: string
  default: "13%"
fifth_column_size:
  type: string
  default: "13%"
first_column_icon:
  type: string
  default: ""
second_column_icon:
  type: string
  default: ""
third_column_icon:
  type: string
  default: ""
fourth_column_icon:
  type: string
  default: ""
fifth_column_icon:
  type: string
  default: ""
