show_for_members:
  type: bool
  default: true
show_for_anon:
  type: bool
  default: true
display_on_mobile:
  type: bool
  default: false
display_on_desktop:
  type: bool
  default: true
display_on_homepage:
  type: bool
  default: true
url_must_contain:
  type: list
  list_type: simple
  # default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*
  default: / # this is for only showing banner on home page 
dismissible:
  type: bool
  default: false
collapsible:
  type: bool
  default: false
default_collapsed_state:
  type: enum
  default: collapsed
  choices:
    - expanded
cookie_lifespan:
  type: enum
  default: none
  choices:
    - minute
    - day
    - week
    - month
    - year
cookie_name:
  type: string
  default: "v1"
full_width_banner:
  type: bool
  default: true
swap_default_positioning:
  type: bool
  default: false
plugin_outlet:
  type: enum
  default: "below-site-header"
  choices:
    - "below-site-header"
    - "above-main-container"
  refresh: true
banner_background_image:
  type: string
  default: ""
banner_background_image_dark:
  type: string
  default: ""
background_color:
  type: string
  default: ""
background_color_dark:
  type: string
  default: ""
primary_text_color:
  type: string
  default: "#141414"
primary_text_color_dark:
  type: string
  default: ""
secondary_text_color:
  type: string
  default: "#FF6C00"
secondary_text_color_dark:
  type: string
  default: ""
link_text_color:
  type: string
  default: "#0f82af"
link_text_color_dark:
  type: string
  default: ""
main_heading_content:
  type: string
  textarea: false
  default: ""
first_column_content:
  type: string
  textarea: true
  default: |
    <figure style="text-align:center;margin:0;">
      <img src="https://placehold.co/120x120?text=Image+1" alt="Image 1" style="max-width:120px;width:100%;height:auto;display:block;margin:0 auto;">
      <figcaption style="font-size:16px;font-weight:700;margin-top:6px;color:#333">Caption under image 1</figcaption>
    </figure>
second_column_content:
  type: string
  textarea: true
  default: |
    <figure style="text-align:center;margin:0;">
      <img src="https://placehold.co/120x120?text=Image+2" alt="Image 2" style="max-width:120px;width:100%;height:auto;display:block;margin:0 auto;">
      <figcaption style="font-size:16px;font-weight:700;margin-top:6px;color:#333">Caption under image 2</figcaption>
    </figure>
third_column_content:
  type: string
  textarea: true
  default: |
    <figure style="text-align:center;margin:0;">
      <img src="https://placehold.co/120x120?text=Image+3" alt="Image 3" style="max-width:120px;width:100%;height:auto;display:block;margin:0 auto;">
      <figcaption style="font-size:16px;font-weight:700;margin-top:6px;color:#333">Caption under image 3</figcaption>
    </figure>
fourth_column_content:
  type: string
  textarea: true
  default: |
    <figure style="text-align:center;margin:0;">
      <img src="https://placehold.co/120x120?text=Image+4" alt="Image 4" style="max-width:120px;width:100%;height:auto;display:block;margin:0 auto;">
      <figcaption style="font-size:16px;font-weight:700;margin-top:6px;color:#333">Caption under image 4</figcaption>
    </figure>
first_column_size:
  type: string
  default: "25%"
second_column_size:
  type: string
  default: "25%"
third_column_size:
  type: string
  default: "25%"
fourth_column_size:
  type: string
  default: "25%"
first_column_icon:
  type: string
  default: ""
second_column_icon:
  type: string
  default: ""
third_column_icon:
  type: string
  default: ""
fourth_column_icon:
  type: string
  default: ""
